$axure.loadCurrentPage({
  "url":"badges.html",
  "generationDate":new Date(1521240872754.82),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"adfc789d95e3407ca62c423319673537",
    "type":"Axure:Page",
    "name":"Badges",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"58bb47789e2b4eee8b2f90be0fee2e47",
          "label":"Edit Frame Target",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":131},
            "size":{
              "width":320,
              "height":509}},
          "adaptiveStyles":{
},
          "target":{
            "targetType":"page",
            "includeVariables":true}},
{
          "id":"e0120111c172492289e47ab1bdadabcb",
          "label":"BG Color",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFF4},
            "location":{
              "x":64,
              "y":145},
            "size":{
              "width":322,
              "height":568},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1bb7f10129f40b7a9a51b535e51590f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFF4},
                "location":{
                  "x":64,
                  "y":145},
                "size":{
                  "width":322,
                  "height":568},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/badges/bg_color_u1.png"}},
{
          "id":"34cc865abb664fccab5384dbbb2c1435",
          "label":"Edit Frame Target",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":145},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "target":{
            "targetType":"page",
            "includeVariables":true}},
{
          "id":"c6116ab10bdd4e3fbea2e22170e40583",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-91,
              "y":-9},
            "size":{
              "width":551,
              "height":648}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7830c6a381f42909ec1466577bc748d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-91,
                  "y":-9},
                "size":{
                  "width":551,
                  "height":648}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/card_-_home_page/u0.jpg"}},
{
          "id":"ecfbb4af5f0544f0a3b841a9ad6f5848",
          "label":"Edit Frame Target",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":111},
            "size":{
              "width":259,
              "height":435}},
          "adaptiveStyles":{
},
          "target":{
            "targetType":"page",
            "includeVariables":true}},
{
          "id":"eae286738c3249debff6a2d3d3ee8aa4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":149,
              "y":149},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68ae79de0dbd492fb1e89181b55e6dc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":149,
                  "y":149},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/card_-_home_page/u40.png"}},
{
          "id":"3402b7ff41354a53b112888e095f8707",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negrita', 'Arial'",
            "fontSize":"24px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF808080,
              "opacity":1},
            "location":{
              "x":193,
              "y":171},
            "size":{
              "width":113,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"cfbdae04964c469ea4bdc20242d8f8c3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":149},
            "size":{
              "width":111,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"143587b3ee7b45118b1163a450898032",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":193,
                  "y":149},
                "size":{
                  "width":111,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/card_-_home_page/u43.jpg"}},
{
          "id":"0e476b3e3fe14cfc971b5f052916859f",
          "label":"Slider texts",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":203},
            "size":{
              "width":212,
              "height":309}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"0eb0803f0f764a959249d61d2dc3af86",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"15fa44e6516b4eafb7731c093ffdd537",
                  "label":"",
                  "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":35},
                    "size":{
                      "width":70,
                      "height":70}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"068e2385eadd48eeadd93f6198ece1e8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":35},
                        "size":{
                          "width":70,
                          "height":70}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/badges/u13.jpg"}},
{
                  "id":"ff55b7387c524dc68deca590ca88d7b1",
                  "label":"",
                  "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":195},
                    "size":{
                      "width":70,
                      "height":70}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"48c14e181e2c4f0eb4fd1d199db5b517",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":195},
                        "size":{
                          "width":70,
                          "height":70}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/badges/u15.jpg"}},
{
                  "id":"7c4aa06a76334bc8a5804e5e1a573cd0",
                  "label":"",
                  "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":115},
                    "size":{
                      "width":70,
                      "height":70}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7ba58153b58941f0b6887c06dceb1665",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":115},
                        "size":{
                          "width":70,
                          "height":70}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/badges/u17.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"f0066e3ecd97496381d32542f57960b6",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1a340feb6d494bebb5b93d81941e9436",
                  "label":"",
                  "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":183,
                      "y":35},
                    "size":{
                      "width":70,
                      "height":70}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2099e5c62a274a96a13e6f8b0b623edf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":183,
                          "y":35},
                        "size":{
                          "width":70,
                          "height":70}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/badges/u13.jpg"}},
{
                  "id":"248fb00070b64e5b8df6a47454e738c7",
                  "label":"",
                  "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":183,
                      "y":195},
                    "size":{
                      "width":70,
                      "height":70}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"85dc0dfc2029469c8136b9bc7e331225",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":183,
                          "y":195},
                        "size":{
                          "width":70,
                          "height":70}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/badges/u15.jpg"}},
{
                  "id":"0d3b610c2a154b009dc061cf5710d0c9",
                  "label":"",
                  "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":183,
                      "y":115},
                    "size":{
                      "width":70,
                      "height":70}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b0e615a4a00043bab4121196e201ae9b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":183,
                          "y":115},
                        "size":{
                          "width":70,
                          "height":70}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/badges/u17.jpg"}},
{
                  "id":"acf42f29bff94036a58214d31a06755c",
                  "label":"",
                  "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "mouseDown":{
                        "fontStyle":"italic"}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFEEDF2C},
                    "location":{
                      "x":0,
                      "y":1},
                    "size":{
                      "width":120,
                      "height":279},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1a95d54f9b96437caa0c06e7f4dcf4b5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "mouseDown":{
                            "fontStyle":"italic"}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFEEDF2C},
                        "location":{
                          "x":0,
                          "y":1},
                        "size":{
                          "width":120,
                          "height":279},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/card_-_home_page/u9.png",
                    "mouseDown~":"images/card_-_home_page/u9.png"}},
{
                  "id":"82f6dc0870b04852b11036ae9859562f",
                  "label":"",
                  "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":89},
                    "size":{
                      "width":21,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b021be7e7d57401e928302aaab2fb825",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":89},
                        "size":{
                          "width":21,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/card_-_home_page/u11.png"}},
{
                  "id":"814ce9cfe7ff46a897cae313c6a2d42b",
                  "label":"",
                  "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":119},
                    "size":{
                      "width":21,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5848793e8624444186040fb6c14b44df",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":119},
                        "size":{
                          "width":21,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/card_-_home_page/u13.png"}},
{
                  "id":"12483e06a95b416cb8a76f5278a7cc0f",
                  "label":"",
                  "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":179},
                    "size":{
                      "width":21,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ac61a90f0796481aa0cca5fb41ef7e6a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":179},
                        "size":{
                          "width":21,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/card_-_home_page/u15.png"}},
{
                  "id":"45315536ac5c493a9a872a6f72f4b6fd",
                  "label":"",
                  "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":147},
                    "size":{
                      "width":21,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2361c7a6207848ed85638a81926bd8f2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":147},
                        "size":{
                          "width":21,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/card_-_home_page/u17.png"}},
{
                  "id":"f40c9448c8b14bcf9c51d84f57a30dff",
                  "label":"",
                  "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":212},
                    "size":{
                      "width":21,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"87c4bd1d75d945cea728470971019a5e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":212},
                        "size":{
                          "width":21,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/card_-_home_page/u19.png"}},
{
                  "id":"2f613450f7034cfb9fc9786c9487886b",
                  "label":"",
                  "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":35,
                      "y":30},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d89820b227c44892bf90281c984b36a6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":35,
                          "y":30},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/card_-_home_page/u21.png"}},
{
                  "id":"ac261bbf067e4912b2b3ffe3ea4ffd0a",
                  "label":"",
                  "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "stateStyles":{
                      "mouseDown":{
                        "fontStyle":"italic"}},
                    "location":{
                      "x":41,
                      "y":92},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e7909711b6d347549187f0e260d10d53",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "stateStyles":{
                          "mouseDown":{
                            "fontStyle":"italic"}},
                        "location":{
                          "x":41,
                          "y":92},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"9ffeb56e8b574577a4d343982af2e754",
                          "label":"",
                          "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                          "panelIndex":1,
                          "type":"hyperlink",
                          "styleType":"hyperlink",
                          "visible":true,
                          "style":{
                            "fontName":"'Arial Negrita', 'Arial'",
                            "fontWeight":"700"},
                          "adaptiveStyles":{
},
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"Open Card - Home Page in Current Window",
                                      "target":{
                                        "targetType":"page",
                                        "url":"card_-_home_page.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true}]}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseDown~":"resources/images/transparent.gif"}},
{
                  "id":"6ae5a47776004770b6b2a4c7f56c0f97",
                  "label":"",
                  "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "stateStyles":{
                      "mouseDown":{
                        "fontStyle":"italic"}},
                    "location":{
                      "x":41,
                      "y":121},
                    "size":{
                      "width":63,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"85d8dddf379847c3802874b8a8c98529",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "stateStyles":{
                          "mouseDown":{
                            "fontStyle":"italic"}},
                        "location":{
                          "x":41,
                          "y":121},
                        "size":{
                          "width":63,
                          "height":16}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"7e4c4df06ed5432f960954b56f0e4ec4",
                          "label":"",
                          "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                          "panelIndex":1,
                          "type":"hyperlink",
                          "styleType":"hyperlink",
                          "visible":true,
                          "style":{
                            "fontName":"'Arial Negrita', 'Arial'",
                            "fontWeight":"700"},
                          "adaptiveStyles":{
},
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"Open Profile in Current Window",
                                      "target":{
                                        "targetType":"page",
                                        "url":"profile.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true}]}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseDown~":"resources/images/transparent.gif"}},
{
                  "id":"8c1e4e4ce0534d2ba94b7ed0e6cce080",
                  "label":"",
                  "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "stateStyles":{
                      "mouseDown":{
                        "fontStyle":"italic"}},
                    "location":{
                      "x":41,
                      "y":182},
                    "size":{
                      "width":76,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2ccc37fa03114c62abb2dfc8166066ef",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "stateStyles":{
                          "mouseDown":{
                            "fontStyle":"italic"}},
                        "location":{
                          "x":41,
                          "y":182},
                        "size":{
                          "width":76,
                          "height":16}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"a0404ca2107b4ee7a842db5b7bd09dec",
                          "label":"",
                          "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                          "panelIndex":1,
                          "type":"hyperlink",
                          "styleType":"hyperlink",
                          "visible":true,
                          "style":{
                            "fontName":"'Arial Negrita', 'Arial'",
                            "fontWeight":"700"},
                          "adaptiveStyles":{
},
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"Open Rewards in Current Window",
                                      "target":{
                                        "targetType":"page",
                                        "url":"rewards.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true}]}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseDown~":"resources/images/transparent.gif"}},
{
                  "id":"8b6a6f7875b347868ae53b212e1dddfc",
                  "label":"",
                  "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "stateStyles":{
                      "mouseDown":{
                        "fontStyle":"italic"}},
                    "location":{
                      "x":41,
                      "y":151},
                    "size":{
                      "width":68,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bc649c13d35c4169aaaae66347abca39",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "stateStyles":{
                          "mouseDown":{
                            "fontStyle":"italic"}},
                        "location":{
                          "x":41,
                          "y":151},
                        "size":{
                          "width":68,
                          "height":16}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"e452473af78147858bc1ff533db359d7",
                          "label":"",
                          "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                          "panelIndex":1,
                          "type":"hyperlink",
                          "styleType":"hyperlink",
                          "visible":true,
                          "style":{
                            "fontName":"'Arial Negrita', 'Arial'",
                            "fontWeight":"700"},
                          "adaptiveStyles":{
},
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"Open Badges in Current Window",
                                      "target":{
                                        "targetType":"page",
                                        "url":"badges.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true}]}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseDown~":"resources/images/transparent.gif"}},
{
                  "id":"66241401f5a8429d91bc0273f8e47e1b",
                  "label":"",
                  "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "stateStyles":{
                      "mouseDown":{
                        "fontStyle":"italic"}},
                    "location":{
                      "x":41,
                      "y":214},
                    "size":{
                      "width":33,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"41333360625b4629af764caad20a511a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "stateStyles":{
                          "mouseDown":{
                            "fontStyle":"italic"}},
                        "location":{
                          "x":41,
                          "y":214},
                        "size":{
                          "width":33,
                          "height":16}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"62cdb84af2c9411daa09e58032ec9384",
                          "label":"",
                          "parentDynamicPanel":"0e476b3e3fe14cfc971b5f052916859f",
                          "panelIndex":1,
                          "type":"hyperlink",
                          "styleType":"hyperlink",
                          "visible":true,
                          "style":{
                            "fontName":"'Arial Negrita', 'Arial'",
                            "fontWeight":"700"},
                          "adaptiveStyles":{
},
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"Open FAQs in Current Window",
                                      "target":{
                                        "targetType":"page",
                                        "url":"faqs.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true}]}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseDown~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"eb609f51274d41c29493708e1882abf5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}}},
            "location":{
              "x":70,
              "y":162},
            "size":{
              "width":49,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36915d9c43f647afab82e125a39c471d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":70,
                  "y":162},
                "size":{
                  "width":49,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Slider texts to Previous fade out 500ms slide right in 500ms wrap",
                      "panelsToStates":[{
                          "panelPath":["0e476b3e3fe14cfc971b5f052916859f"],
                          "stateInfo":{
                            "setStateType":"previous",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "options":{
                              "animateOut":{
                                "easing":"fade",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideRight",
                                "duration":500},
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/card_-_home_page/u38.png",
            "mouseOver~":"images/card_-_home_page/u38_mouseOver.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "58bb47789e2b4eee8b2f90be0fee2e47":{
      "scriptId":"u0"},
    "e0120111c172492289e47ab1bdadabcb":{
      "scriptId":"u1"},
    "b1bb7f10129f40b7a9a51b535e51590f":{
      "scriptId":"u2"},
    "34cc865abb664fccab5384dbbb2c1435":{
      "scriptId":"u3"},
    "c6116ab10bdd4e3fbea2e22170e40583":{
      "scriptId":"u4"},
    "f7830c6a381f42909ec1466577bc748d":{
      "scriptId":"u5"},
    "ecfbb4af5f0544f0a3b841a9ad6f5848":{
      "scriptId":"u6"},
    "eae286738c3249debff6a2d3d3ee8aa4":{
      "scriptId":"u7"},
    "68ae79de0dbd492fb1e89181b55e6dc0":{
      "scriptId":"u8"},
    "3402b7ff41354a53b112888e095f8707":{
      "scriptId":"u9"},
    "cfbdae04964c469ea4bdc20242d8f8c3":{
      "scriptId":"u10"},
    "143587b3ee7b45118b1163a450898032":{
      "scriptId":"u11"},
    "0e476b3e3fe14cfc971b5f052916859f":{
      "scriptId":"u12"},
    "15fa44e6516b4eafb7731c093ffdd537":{
      "scriptId":"u13"},
    "068e2385eadd48eeadd93f6198ece1e8":{
      "scriptId":"u14"},
    "ff55b7387c524dc68deca590ca88d7b1":{
      "scriptId":"u15"},
    "48c14e181e2c4f0eb4fd1d199db5b517":{
      "scriptId":"u16"},
    "7c4aa06a76334bc8a5804e5e1a573cd0":{
      "scriptId":"u17"},
    "7ba58153b58941f0b6887c06dceb1665":{
      "scriptId":"u18"},
    "1a340feb6d494bebb5b93d81941e9436":{
      "scriptId":"u19"},
    "2099e5c62a274a96a13e6f8b0b623edf":{
      "scriptId":"u20"},
    "248fb00070b64e5b8df6a47454e738c7":{
      "scriptId":"u21"},
    "85dc0dfc2029469c8136b9bc7e331225":{
      "scriptId":"u22"},
    "0d3b610c2a154b009dc061cf5710d0c9":{
      "scriptId":"u23"},
    "b0e615a4a00043bab4121196e201ae9b":{
      "scriptId":"u24"},
    "acf42f29bff94036a58214d31a06755c":{
      "scriptId":"u25"},
    "1a95d54f9b96437caa0c06e7f4dcf4b5":{
      "scriptId":"u26"},
    "82f6dc0870b04852b11036ae9859562f":{
      "scriptId":"u27"},
    "b021be7e7d57401e928302aaab2fb825":{
      "scriptId":"u28"},
    "814ce9cfe7ff46a897cae313c6a2d42b":{
      "scriptId":"u29"},
    "5848793e8624444186040fb6c14b44df":{
      "scriptId":"u30"},
    "12483e06a95b416cb8a76f5278a7cc0f":{
      "scriptId":"u31"},
    "ac61a90f0796481aa0cca5fb41ef7e6a":{
      "scriptId":"u32"},
    "45315536ac5c493a9a872a6f72f4b6fd":{
      "scriptId":"u33"},
    "2361c7a6207848ed85638a81926bd8f2":{
      "scriptId":"u34"},
    "f40c9448c8b14bcf9c51d84f57a30dff":{
      "scriptId":"u35"},
    "87c4bd1d75d945cea728470971019a5e":{
      "scriptId":"u36"},
    "2f613450f7034cfb9fc9786c9487886b":{
      "scriptId":"u37"},
    "d89820b227c44892bf90281c984b36a6":{
      "scriptId":"u38"},
    "ac261bbf067e4912b2b3ffe3ea4ffd0a":{
      "scriptId":"u39"},
    "e7909711b6d347549187f0e260d10d53":{
      "scriptId":"u40"},
    "9ffeb56e8b574577a4d343982af2e754":{
      "scriptId":"u41"},
    "6ae5a47776004770b6b2a4c7f56c0f97":{
      "scriptId":"u42"},
    "85d8dddf379847c3802874b8a8c98529":{
      "scriptId":"u43"},
    "7e4c4df06ed5432f960954b56f0e4ec4":{
      "scriptId":"u44"},
    "8c1e4e4ce0534d2ba94b7ed0e6cce080":{
      "scriptId":"u45"},
    "2ccc37fa03114c62abb2dfc8166066ef":{
      "scriptId":"u46"},
    "a0404ca2107b4ee7a842db5b7bd09dec":{
      "scriptId":"u47"},
    "8b6a6f7875b347868ae53b212e1dddfc":{
      "scriptId":"u48"},
    "bc649c13d35c4169aaaae66347abca39":{
      "scriptId":"u49"},
    "e452473af78147858bc1ff533db359d7":{
      "scriptId":"u50"},
    "66241401f5a8429d91bc0273f8e47e1b":{
      "scriptId":"u51"},
    "41333360625b4629af764caad20a511a":{
      "scriptId":"u52"},
    "62cdb84af2c9411daa09e58032ec9384":{
      "scriptId":"u53"},
    "eb609f51274d41c29493708e1882abf5":{
      "scriptId":"u54"},
    "36915d9c43f647afab82e125a39c471d":{
      "scriptId":"u55"}}});