$axure.loadCurrentPage({
  "url":"card_-_home_page.html",
  "generationDate":new Date(1521240872355.53),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"59342e6da58b49cf875c1f6d105a72b6",
    "type":"Axure:Page",
    "name":"Card - Home Page",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3205198ba27e4a8ba77714c7752a24d2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-91,
              "y":-9},
            "size":{
              "width":551,
              "height":648}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5540e8137bd9452991e0e0d4d9e03eeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-91,
                  "y":-9},
                "size":{
                  "width":551,
                  "height":648}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/card_-_home_page/u0.jpg"}},
{
          "id":"2d749fe2f3c148c4b6f541dbbab445ff",
          "label":"Edit Frame Target",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":111},
            "size":{
              "width":259,
              "height":435}},
          "adaptiveStyles":{
},
          "target":{
            "targetType":"page",
            "includeVariables":true}},
{
          "id":"e2c357a49da042ef8638bfcd32f826fd",
          "label":"Slider texts",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":203},
            "size":{
              "width":213,
              "height":309}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"4ed061c7c3e647d89a3e753f661bdc81",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d4462a0f1a1a48b5adb89dce1d7f5808",
                  "label":"",
                  "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":15,
                      "y":12},
                    "size":{
                      "width":203,
                      "height":128}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6e30af801a544b899795a7c2b6143945",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":15,
                          "y":12},
                        "size":{
                          "width":203,
                          "height":128}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/card_-_home_page/u4.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"4878a0d7cf9d4a509d27b84960a68918",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"058e7a2a9a524a009b7e6c92d05c75fc",
                  "label":"",
                  "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                  "panelIndex":1,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":800,
                      "y":176},
                    "size":{
                      "width":200,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/card_-_home_page/u6_line.png"}},
{
                  "id":"01b7fb161e5a4a07a3c4e031cb413a39",
                  "label":"",
                  "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":140,
                      "y":12},
                    "size":{
                      "width":203,
                      "height":128}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"30eb5f71189146639ee81a35b35b47f2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":140,
                          "y":12},
                        "size":{
                          "width":203,
                          "height":128}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/card_-_home_page/u4.jpg"}},
{
                  "id":"ad145e58d791436d9e5b2e2d1c13fb43",
                  "label":"",
                  "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "mouseDown":{
                        "fontStyle":"italic"}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFEEDF2C},
                    "location":{
                      "x":0,
                      "y":1},
                    "size":{
                      "width":120,
                      "height":279},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4c7a2c6387944a258068941b8c21516b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "mouseDown":{
                            "fontStyle":"italic"}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFEEDF2C},
                        "location":{
                          "x":0,
                          "y":1},
                        "size":{
                          "width":120,
                          "height":279},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/card_-_home_page/u9.png",
                    "mouseDown~":"images/card_-_home_page/u9.png"}},
{
                  "id":"1e74bb134f374c17addc1ac2d24f8629",
                  "label":"",
                  "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":89},
                    "size":{
                      "width":21,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"020e40342b1b41c292a1076498b8d227",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":89},
                        "size":{
                          "width":21,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/card_-_home_page/u11.png"}},
{
                  "id":"3449a82d158f40289ba7748be81ebd62",
                  "label":"",
                  "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":119},
                    "size":{
                      "width":21,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5e5710d1e17742ee86aff08d601da00f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":119},
                        "size":{
                          "width":21,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/card_-_home_page/u13.png"}},
{
                  "id":"4cab6d9eb687409baa5c88814d460954",
                  "label":"",
                  "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":179},
                    "size":{
                      "width":21,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dd97a7f21e1d413a81c5cb8a917c2b02",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":179},
                        "size":{
                          "width":21,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/card_-_home_page/u15.png"}},
{
                  "id":"c5bae35cf6d6422dab0605da143d0951",
                  "label":"",
                  "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":147},
                    "size":{
                      "width":21,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c1c3a518471b4543a140ee629b39814b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":147},
                        "size":{
                          "width":21,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/card_-_home_page/u17.png"}},
{
                  "id":"990e29dc2df74dc1ae72681a2976dbc9",
                  "label":"",
                  "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":212},
                    "size":{
                      "width":21,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"84357aa20fb542b987aa6a661e0ab60f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":212},
                        "size":{
                          "width":21,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/card_-_home_page/u19.png"}},
{
                  "id":"67bca5a485e04922897650765d097bd4",
                  "label":"",
                  "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":35,
                      "y":30},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"80d358f8f5114015aa0a12ee43aa7fef",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":35,
                          "y":30},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/card_-_home_page/u21.png"}},
{
                  "id":"711f49dfbe034048b49ab7e0ab049595",
                  "label":"",
                  "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "stateStyles":{
                      "mouseDown":{
                        "fontStyle":"italic"}},
                    "location":{
                      "x":41,
                      "y":92},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"235141dac05a4e6082c39132ead5ec12",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "stateStyles":{
                          "mouseDown":{
                            "fontStyle":"italic"}},
                        "location":{
                          "x":41,
                          "y":92},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"496274bda43a4221adfbed059102e97a",
                          "label":"",
                          "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                          "panelIndex":1,
                          "type":"hyperlink",
                          "styleType":"hyperlink",
                          "visible":true,
                          "style":{
                            "fontName":"'Arial Negrita', 'Arial'",
                            "fontWeight":"700"},
                          "adaptiveStyles":{
},
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"Open Card - Home Page in Current Window",
                                      "target":{
                                        "targetType":"page",
                                        "url":"card_-_home_page.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true}]}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseDown~":"resources/images/transparent.gif"}},
{
                  "id":"661694cc0fdc4da6b6a2bc1eff265b8e",
                  "label":"",
                  "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "stateStyles":{
                      "mouseDown":{
                        "fontStyle":"italic"}},
                    "location":{
                      "x":41,
                      "y":121},
                    "size":{
                      "width":63,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"02473c9d675f41669c287aab8fd09199",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "stateStyles":{
                          "mouseDown":{
                            "fontStyle":"italic"}},
                        "location":{
                          "x":41,
                          "y":121},
                        "size":{
                          "width":63,
                          "height":16}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"d29b6c6fb2ae4df09df307bb2266d4c0",
                          "label":"",
                          "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                          "panelIndex":1,
                          "type":"hyperlink",
                          "styleType":"hyperlink",
                          "visible":true,
                          "style":{
                            "fontName":"'Arial Negrita', 'Arial'",
                            "fontWeight":"700"},
                          "adaptiveStyles":{
},
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"Open Profile in Current Window",
                                      "target":{
                                        "targetType":"page",
                                        "url":"profile.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true}]}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseDown~":"resources/images/transparent.gif"}},
{
                  "id":"5a5f447713f148a5b1e2cf8788e0d370",
                  "label":"",
                  "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "stateStyles":{
                      "mouseDown":{
                        "fontStyle":"italic"}},
                    "location":{
                      "x":41,
                      "y":182},
                    "size":{
                      "width":76,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8dbbcb40312e42c2a521ca14f458b68d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "stateStyles":{
                          "mouseDown":{
                            "fontStyle":"italic"}},
                        "location":{
                          "x":41,
                          "y":182},
                        "size":{
                          "width":76,
                          "height":16}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"0f87223a7c044c39bd5b5c721c431b4a",
                          "label":"",
                          "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                          "panelIndex":1,
                          "type":"hyperlink",
                          "styleType":"hyperlink",
                          "visible":true,
                          "style":{
                            "fontName":"'Arial Negrita', 'Arial'",
                            "fontWeight":"700"},
                          "adaptiveStyles":{
},
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"Open Rewards in Current Window",
                                      "target":{
                                        "targetType":"page",
                                        "url":"rewards.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true}]}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseDown~":"resources/images/transparent.gif"}},
{
                  "id":"472ef6e4410c40b0b3ebbc141e540bb9",
                  "label":"",
                  "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "stateStyles":{
                      "mouseDown":{
                        "fontStyle":"italic"}},
                    "location":{
                      "x":41,
                      "y":151},
                    "size":{
                      "width":68,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"df7ecd2f165347a3937f62502de3ae4f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "stateStyles":{
                          "mouseDown":{
                            "fontStyle":"italic"}},
                        "location":{
                          "x":41,
                          "y":151},
                        "size":{
                          "width":68,
                          "height":16}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"28819e5fde404dbb896eb259a1f42de3",
                          "label":"",
                          "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                          "panelIndex":1,
                          "type":"hyperlink",
                          "styleType":"hyperlink",
                          "visible":true,
                          "style":{
                            "fontName":"'Arial Negrita', 'Arial'",
                            "fontWeight":"700"},
                          "adaptiveStyles":{
},
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"Open Badges in Current Window",
                                      "target":{
                                        "targetType":"page",
                                        "url":"badges.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true}]}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseDown~":"resources/images/transparent.gif"}},
{
                  "id":"e6bf435f44584adca9ca79953327c3c8",
                  "label":"",
                  "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "stateStyles":{
                      "mouseDown":{
                        "fontStyle":"italic"}},
                    "location":{
                      "x":41,
                      "y":214},
                    "size":{
                      "width":33,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5a6d3159dc73480788ff70f11f5ca37e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "stateStyles":{
                          "mouseDown":{
                            "fontStyle":"italic"}},
                        "location":{
                          "x":41,
                          "y":214},
                        "size":{
                          "width":33,
                          "height":16}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"41b4e2b9b01349db9b47c936e01d6eda",
                          "label":"",
                          "parentDynamicPanel":"e2c357a49da042ef8638bfcd32f826fd",
                          "panelIndex":1,
                          "type":"hyperlink",
                          "styleType":"hyperlink",
                          "visible":true,
                          "style":{
                            "fontName":"'Arial Negrita', 'Arial'",
                            "fontWeight":"700"},
                          "adaptiveStyles":{
},
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"Open FAQs in Current Window",
                                      "target":{
                                        "targetType":"page",
                                        "url":"faqs.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true}]}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseDown~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"c7258438e806445c91677d0f9acdb825",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}}},
            "location":{
              "x":70,
              "y":162},
            "size":{
              "width":49,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"947a52dc61ad417583e7948ce2fcb471",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":70,
                  "y":162},
                "size":{
                  "width":49,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Slider texts to Previous fade out 500ms slide right in 500ms wrap",
                      "panelsToStates":[{
                          "panelPath":["e2c357a49da042ef8638bfcd32f826fd"],
                          "stateInfo":{
                            "setStateType":"previous",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "options":{
                              "animateOut":{
                                "easing":"fade",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideRight",
                                "duration":500},
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/card_-_home_page/u38.png",
            "mouseOver~":"images/card_-_home_page/u38_mouseOver.png"}},
{
          "id":"597977fe4b024f319d73e3ec9d30bc7f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":149,
              "y":149},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf3dd42e163940b8bcecf77de60e3efa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":149,
                  "y":149},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/card_-_home_page/u40.png"}},
{
          "id":"c3815c2c385a45fcb05df99d26231f07",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negrita', 'Arial'",
            "fontSize":"24px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF808080,
              "opacity":1},
            "location":{
              "x":193,
              "y":171},
            "size":{
              "width":113,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"456d903158fd40409add2130339f6f2d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":149},
            "size":{
              "width":111,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8795be616be24ac580828bcd46154108",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":193,
                  "y":149},
                "size":{
                  "width":111,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/card_-_home_page/u43.jpg"}},
{
          "id":"a1d9069b7621472490ccb7212b79d114",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":99.5,
              "y":340},
            "size":{
              "width":170,
              "height":70}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onLoad":{
              "description":"OnLoad",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"wait",
                      "description":"Wait 2000 ms",
                      "waitTime":2000},
{
                      "action":"setPanelState",
                      "description":"Set (Dynamic Panel) to State2 fade out 500ms fade in 500ms",
                      "panelsToStates":[{
                          "panelPath":["a1d9069b7621472490ccb7212b79d114"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "animateOut":{
                                "easing":"fade",
                                "duration":500},
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"5e5a22b7a079417d9b1176363b0b1a18",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f3c303c479f1444683d3aabbd173cd82",
                  "label":"",
                  "parentDynamicPanel":"a1d9069b7621472490ccb7212b79d114",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negrita', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF0000},
                    "location":{
                      "x":30,
                      "y":20},
                    "size":{
                      "width":100,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6fbf97887b3d4c11a4c4b560e93a9b95",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a1d9069b7621472490ccb7212b79d114",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negrita', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF0000},
                        "location":{
                          "x":30,
                          "y":20},
                        "size":{
                          "width":100,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/card_-_home_page/u46.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"d9f988f976b74cfdabdb39b3a705d878",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7dbfe489a36542b1a2f592d4a0dc458b",
                  "label":"",
                  "parentDynamicPanel":"a1d9069b7621472490ccb7212b79d114",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negrita', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF00FF00},
                    "location":{
                      "x":30,
                      "y":20},
                    "size":{
                      "width":100,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1f76a541a1b4443b94058cb79b9e105d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a1d9069b7621472490ccb7212b79d114",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negrita', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF00FF00},
                        "location":{
                          "x":30,
                          "y":20},
                        "size":{
                          "width":100,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/card_-_home_page/u48.png"}},
{
                  "id":"ec514bf595664a03b6f0d457a9b4fc4a",
                  "label":"",
                  "parentDynamicPanel":"a1d9069b7621472490ccb7212b79d114",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":50},
                    "size":{
                      "width":140,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"415e5688eb8f4766a8a624530f121bcd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a1d9069b7621472490ccb7212b79d114",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":50},
                        "size":{
                          "width":140,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "3205198ba27e4a8ba77714c7752a24d2":{
      "scriptId":"u0"},
    "5540e8137bd9452991e0e0d4d9e03eeb":{
      "scriptId":"u1"},
    "2d749fe2f3c148c4b6f541dbbab445ff":{
      "scriptId":"u2"},
    "e2c357a49da042ef8638bfcd32f826fd":{
      "scriptId":"u3"},
    "d4462a0f1a1a48b5adb89dce1d7f5808":{
      "scriptId":"u4"},
    "6e30af801a544b899795a7c2b6143945":{
      "scriptId":"u5"},
    "058e7a2a9a524a009b7e6c92d05c75fc":{
      "scriptId":"u6"},
    "01b7fb161e5a4a07a3c4e031cb413a39":{
      "scriptId":"u7"},
    "30eb5f71189146639ee81a35b35b47f2":{
      "scriptId":"u8"},
    "ad145e58d791436d9e5b2e2d1c13fb43":{
      "scriptId":"u9"},
    "4c7a2c6387944a258068941b8c21516b":{
      "scriptId":"u10"},
    "1e74bb134f374c17addc1ac2d24f8629":{
      "scriptId":"u11"},
    "020e40342b1b41c292a1076498b8d227":{
      "scriptId":"u12"},
    "3449a82d158f40289ba7748be81ebd62":{
      "scriptId":"u13"},
    "5e5710d1e17742ee86aff08d601da00f":{
      "scriptId":"u14"},
    "4cab6d9eb687409baa5c88814d460954":{
      "scriptId":"u15"},
    "dd97a7f21e1d413a81c5cb8a917c2b02":{
      "scriptId":"u16"},
    "c5bae35cf6d6422dab0605da143d0951":{
      "scriptId":"u17"},
    "c1c3a518471b4543a140ee629b39814b":{
      "scriptId":"u18"},
    "990e29dc2df74dc1ae72681a2976dbc9":{
      "scriptId":"u19"},
    "84357aa20fb542b987aa6a661e0ab60f":{
      "scriptId":"u20"},
    "67bca5a485e04922897650765d097bd4":{
      "scriptId":"u21"},
    "80d358f8f5114015aa0a12ee43aa7fef":{
      "scriptId":"u22"},
    "711f49dfbe034048b49ab7e0ab049595":{
      "scriptId":"u23"},
    "235141dac05a4e6082c39132ead5ec12":{
      "scriptId":"u24"},
    "496274bda43a4221adfbed059102e97a":{
      "scriptId":"u25"},
    "661694cc0fdc4da6b6a2bc1eff265b8e":{
      "scriptId":"u26"},
    "02473c9d675f41669c287aab8fd09199":{
      "scriptId":"u27"},
    "d29b6c6fb2ae4df09df307bb2266d4c0":{
      "scriptId":"u28"},
    "5a5f447713f148a5b1e2cf8788e0d370":{
      "scriptId":"u29"},
    "8dbbcb40312e42c2a521ca14f458b68d":{
      "scriptId":"u30"},
    "0f87223a7c044c39bd5b5c721c431b4a":{
      "scriptId":"u31"},
    "472ef6e4410c40b0b3ebbc141e540bb9":{
      "scriptId":"u32"},
    "df7ecd2f165347a3937f62502de3ae4f":{
      "scriptId":"u33"},
    "28819e5fde404dbb896eb259a1f42de3":{
      "scriptId":"u34"},
    "e6bf435f44584adca9ca79953327c3c8":{
      "scriptId":"u35"},
    "5a6d3159dc73480788ff70f11f5ca37e":{
      "scriptId":"u36"},
    "41b4e2b9b01349db9b47c936e01d6eda":{
      "scriptId":"u37"},
    "c7258438e806445c91677d0f9acdb825":{
      "scriptId":"u38"},
    "947a52dc61ad417583e7948ce2fcb471":{
      "scriptId":"u39"},
    "597977fe4b024f319d73e3ec9d30bc7f":{
      "scriptId":"u40"},
    "bf3dd42e163940b8bcecf77de60e3efa":{
      "scriptId":"u41"},
    "c3815c2c385a45fcb05df99d26231f07":{
      "scriptId":"u42"},
    "456d903158fd40409add2130339f6f2d":{
      "scriptId":"u43"},
    "8795be616be24ac580828bcd46154108":{
      "scriptId":"u44"},
    "a1d9069b7621472490ccb7212b79d114":{
      "scriptId":"u45"},
    "f3c303c479f1444683d3aabbd173cd82":{
      "scriptId":"u46"},
    "6fbf97887b3d4c11a4c4b560e93a9b95":{
      "scriptId":"u47"},
    "7dbfe489a36542b1a2f592d4a0dc458b":{
      "scriptId":"u48"},
    "1f76a541a1b4443b94058cb79b9e105d":{
      "scriptId":"u49"},
    "ec514bf595664a03b6f0d457a9b4fc4a":{
      "scriptId":"u50"},
    "415e5688eb8f4766a8a624530f121bcd":{
      "scriptId":"u51"}}});