$axure.loadCurrentPage({
  "url":"faqs.html",
  "generationDate":new Date(1521240873099.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"379ff8ba80844723ab4a30d1f3c78b1b",
    "type":"Axure:Page",
    "name":"FAQs",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ebfb2981fb2a473591998f7096a5c368",
          "label":"Edit Frame Target",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":121},
            "size":{
              "width":320,
              "height":509}},
          "adaptiveStyles":{
},
          "target":{
            "targetType":"page",
            "includeVariables":true}},
{
          "id":"229397f2904c4338bc743f06d59b0c7a",
          "label":"BG Color",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFF4},
            "location":{
              "x":54,
              "y":135},
            "size":{
              "width":322,
              "height":568},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26cf5eeed7d84da1bc41e7e0c1f7c19c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFF4},
                "location":{
                  "x":54,
                  "y":135},
                "size":{
                  "width":322,
                  "height":568},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/badges/bg_color_u1.png"}},
{
          "id":"bf8b7df05e0b478790314df6b1479bd6",
          "label":"Edit Frame Target",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":135},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "target":{
            "targetType":"page",
            "includeVariables":true}},
{
          "id":"82255c2ed0e04b79b8f33ae3e1a71b62",
          "label":"BG Color",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFF4},
            "location":{
              "x":64,
              "y":145},
            "size":{
              "width":322,
              "height":568},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6bd52ed3a8f408ea8163b28b508e10b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFF4},
                "location":{
                  "x":64,
                  "y":145},
                "size":{
                  "width":322,
                  "height":568},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/badges/bg_color_u1.png"}},
{
          "id":"0b65c3c5be474b34942b48496b9d1831",
          "label":"Edit Frame Target",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":145},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "target":{
            "targetType":"page",
            "includeVariables":true}},
{
          "id":"50bf048137924667a8fc5c813dc326b2",
          "label":"Edit Frame Target",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":131},
            "size":{
              "width":320,
              "height":509}},
          "adaptiveStyles":{
},
          "target":{
            "targetType":"page",
            "includeVariables":true}},
{
          "id":"df29119ed6b046bdbfea47f775eb45e8",
          "label":"BG Color",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFF4},
            "location":{
              "x":64,
              "y":145},
            "size":{
              "width":322,
              "height":568},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b055a2e8875489d924ec6910d2f030d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFF4},
                "location":{
                  "x":64,
                  "y":145},
                "size":{
                  "width":322,
                  "height":568},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/badges/bg_color_u1.png"}},
{
          "id":"6810cb829cf74272bcf90903de100ab0",
          "label":"Edit Frame Target",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":145},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "target":{
            "targetType":"page",
            "includeVariables":true}},
{
          "id":"517c1b04ceef47e7a4873100e3012b09",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-91,
              "y":-9},
            "size":{
              "width":551,
              "height":648}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1428410928e4564ab4b04d8ebfa17fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-91,
                  "y":-9},
                "size":{
                  "width":551,
                  "height":648}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/card_-_home_page/u0.jpg"}},
{
          "id":"cd4b6329e14446dda9838c14621e0989",
          "label":"Edit Frame Target",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":111},
            "size":{
              "width":259,
              "height":435}},
          "adaptiveStyles":{
},
          "target":{
            "targetType":"page",
            "includeVariables":true}},
{
          "id":"e66e2c03650a4506b145aff10a75041f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":149,
              "y":149},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6d89e8ec17c4d819d8d5e3719a1c633",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":149,
                  "y":149},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/card_-_home_page/u40.png"}},
{
          "id":"5ec44c104f6a454bab89a78116c95ae0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negrita', 'Arial'",
            "fontSize":"24px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF808080,
              "opacity":1},
            "location":{
              "x":193,
              "y":171},
            "size":{
              "width":113,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"58b9e83c443c46bf878e8e9f65c4a1be",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":149},
            "size":{
              "width":111,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c86f36d03ce448e1bd5b73840c8d8cce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":193,
                  "y":149},
                "size":{
                  "width":111,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/card_-_home_page/u43.jpg"}},
{
          "id":"54cb98d1cb734d3d9c5758113c3857d2",
          "label":"Slider texts",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":203},
            "size":{
              "width":213,
              "height":309}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"47d0bb92488c4c2b89e467cc58855e8d",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b85b1096ba9c40b695566ad0f4b5b879",
                  "label":"",
                  "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"48px",
                    "location":{
                      "x":40,
                      "y":10},
                    "size":{
                      "width":120,
                      "height":57}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"41d457efc2a342f6ae4302a7623f9d15",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"48px",
                        "location":{
                          "x":40,
                          "y":10},
                        "size":{
                          "width":120,
                          "height":57}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"946ccaca192141f7a1f65bd66b7bdd86",
                  "label":"",
                  "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":73},
                    "size":{
                      "width":193,
                      "height":220}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6d43905bfaba419ca096ee72f7115d34",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":73},
                        "size":{
                          "width":193,
                          "height":220}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"1062d15a6e654d74b2f214accfc49e5b",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"400f6af72f3d43639a8ba18342b05117",
                  "label":"",
                  "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "mouseDown":{
                        "fontStyle":"italic"}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFEEDF2C},
                    "location":{
                      "x":0,
                      "y":1},
                    "size":{
                      "width":120,
                      "height":279},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1b38f6ac55e04de4806f6ef3b58064d8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "mouseDown":{
                            "fontStyle":"italic"}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFEEDF2C},
                        "location":{
                          "x":0,
                          "y":1},
                        "size":{
                          "width":120,
                          "height":279},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/card_-_home_page/u9.png",
                    "mouseDown~":"images/card_-_home_page/u9.png"}},
{
                  "id":"01c1ae17c6204118ace9ff9b952584b9",
                  "label":"",
                  "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":89},
                    "size":{
                      "width":21,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5cd7093eb9aa40b59fcee7e114917b57",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":89},
                        "size":{
                          "width":21,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/card_-_home_page/u11.png"}},
{
                  "id":"a6d21ea8275b49d09e6f659c202ce544",
                  "label":"",
                  "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":119},
                    "size":{
                      "width":21,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c3ac1ca1d52a49abad25f16c200066c0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":119},
                        "size":{
                          "width":21,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/card_-_home_page/u13.png"}},
{
                  "id":"eca056f5095f49bc80ffd9880abbb6fc",
                  "label":"",
                  "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":179},
                    "size":{
                      "width":21,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7cbac792eda3414383d94ad958a44161",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":179},
                        "size":{
                          "width":21,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/card_-_home_page/u15.png"}},
{
                  "id":"049097ddfdc9488e823f6e4346c85969",
                  "label":"",
                  "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":147},
                    "size":{
                      "width":21,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"53562a64a15b4fbabea37a78af9697f4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":147},
                        "size":{
                          "width":21,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/card_-_home_page/u17.png"}},
{
                  "id":"5ecaee34f32c402e9c87f948c2303c40",
                  "label":"",
                  "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":212},
                    "size":{
                      "width":21,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"94b5ebc76680400f886d690eef0ea6fb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":212},
                        "size":{
                          "width":21,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/card_-_home_page/u19.png"}},
{
                  "id":"f39db920fb8842cca1e2e44033866089",
                  "label":"",
                  "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":35,
                      "y":30},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9f4ae739a1c84583a84bc50f67451b94",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":35,
                          "y":30},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/card_-_home_page/u21.png"}},
{
                  "id":"f05e5a7189cc4e4594c9f59902235179",
                  "label":"",
                  "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "stateStyles":{
                      "mouseDown":{
                        "fontStyle":"italic"}},
                    "location":{
                      "x":41,
                      "y":92},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"256bec01c0d34179a305125a9b3fd33b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "stateStyles":{
                          "mouseDown":{
                            "fontStyle":"italic"}},
                        "location":{
                          "x":41,
                          "y":92},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"415a19dec1b347168563399dfbcee1be",
                          "label":"",
                          "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                          "panelIndex":1,
                          "type":"hyperlink",
                          "styleType":"hyperlink",
                          "visible":true,
                          "style":{
                            "fontName":"'Arial Negrita', 'Arial'",
                            "fontWeight":"700"},
                          "adaptiveStyles":{
},
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"Open Card - Home Page in Current Window",
                                      "target":{
                                        "targetType":"page",
                                        "url":"card_-_home_page.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true}]}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseDown~":"resources/images/transparent.gif"}},
{
                  "id":"a5b63f9c94df4ae089572fa0bbf816c1",
                  "label":"",
                  "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "stateStyles":{
                      "mouseDown":{
                        "fontStyle":"italic"}},
                    "location":{
                      "x":41,
                      "y":121},
                    "size":{
                      "width":63,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4b0812cdd8984cc384a1fe730b2d83be",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "stateStyles":{
                          "mouseDown":{
                            "fontStyle":"italic"}},
                        "location":{
                          "x":41,
                          "y":121},
                        "size":{
                          "width":63,
                          "height":16}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"f13a0328d4574ae0a4842f0f33214bf5",
                          "label":"",
                          "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                          "panelIndex":1,
                          "type":"hyperlink",
                          "styleType":"hyperlink",
                          "visible":true,
                          "style":{
                            "fontName":"'Arial Negrita', 'Arial'",
                            "fontWeight":"700"},
                          "adaptiveStyles":{
},
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"Open Profile in Current Window",
                                      "target":{
                                        "targetType":"page",
                                        "url":"profile.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true}]}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseDown~":"resources/images/transparent.gif"}},
{
                  "id":"2d852fb4049240178c4418099436a48d",
                  "label":"",
                  "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "stateStyles":{
                      "mouseDown":{
                        "fontStyle":"italic"}},
                    "location":{
                      "x":41,
                      "y":182},
                    "size":{
                      "width":76,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6d7b297724214ae3b2099dde8ece4713",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "stateStyles":{
                          "mouseDown":{
                            "fontStyle":"italic"}},
                        "location":{
                          "x":41,
                          "y":182},
                        "size":{
                          "width":76,
                          "height":16}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"1f14201c734645a1b4ef5d99c5218ed4",
                          "label":"",
                          "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                          "panelIndex":1,
                          "type":"hyperlink",
                          "styleType":"hyperlink",
                          "visible":true,
                          "style":{
                            "fontName":"'Arial Negrita', 'Arial'",
                            "fontWeight":"700"},
                          "adaptiveStyles":{
},
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"Open Rewards in Current Window",
                                      "target":{
                                        "targetType":"page",
                                        "url":"rewards.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true}]}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseDown~":"resources/images/transparent.gif"}},
{
                  "id":"c8d16d3af28c49988eb32d7463a40d5e",
                  "label":"",
                  "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "stateStyles":{
                      "mouseDown":{
                        "fontStyle":"italic"}},
                    "location":{
                      "x":41,
                      "y":151},
                    "size":{
                      "width":68,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1ec3896ac9d14820ad2deb18bd5135b1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "stateStyles":{
                          "mouseDown":{
                            "fontStyle":"italic"}},
                        "location":{
                          "x":41,
                          "y":151},
                        "size":{
                          "width":68,
                          "height":16}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"d6bb3d44684c4ad39bf5f74e3bca0b1d",
                          "label":"",
                          "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                          "panelIndex":1,
                          "type":"hyperlink",
                          "styleType":"hyperlink",
                          "visible":true,
                          "style":{
                            "fontName":"'Arial Negrita', 'Arial'",
                            "fontWeight":"700"},
                          "adaptiveStyles":{
},
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"Open Badges in Current Window",
                                      "target":{
                                        "targetType":"page",
                                        "url":"badges.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true}]}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseDown~":"resources/images/transparent.gif"}},
{
                  "id":"735a5a788e57441e8ee70200a9621496",
                  "label":"",
                  "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "stateStyles":{
                      "mouseDown":{
                        "fontStyle":"italic"}},
                    "location":{
                      "x":41,
                      "y":214},
                    "size":{
                      "width":33,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ee97077a8a77498885cf29630b74e971",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "stateStyles":{
                          "mouseDown":{
                            "fontStyle":"italic"}},
                        "location":{
                          "x":41,
                          "y":214},
                        "size":{
                          "width":33,
                          "height":16}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"08ef55660d87405a81b5851c35ba285a",
                          "label":"",
                          "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                          "panelIndex":1,
                          "type":"hyperlink",
                          "styleType":"hyperlink",
                          "visible":true,
                          "style":{
                            "fontName":"'Arial Negrita', 'Arial'",
                            "fontWeight":"700"},
                          "adaptiveStyles":{
},
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"Open FAQs in Current Window",
                                      "target":{
                                        "targetType":"page",
                                        "url":"faqs.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true}]}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseDown~":"resources/images/transparent.gif"}},
{
                  "id":"3c12ea5c7ee14302a99dc54083a9e8a4",
                  "label":"",
                  "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"48px",
                    "location":{
                      "x":157,
                      "y":10},
                    "size":{
                      "width":120,
                      "height":57}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4d5d29fafda54fd9acc6c9df0a8227e8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"48px",
                        "location":{
                          "x":157,
                          "y":10},
                        "size":{
                          "width":120,
                          "height":57}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"00b251edc9d344d8826965e06802751a",
                  "label":"",
                  "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":127,
                      "y":73},
                    "size":{
                      "width":193,
                      "height":220}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"217dcc42c0e34278aff717b2bf923ff1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"54cb98d1cb734d3d9c5758113c3857d2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":127,
                          "y":73},
                        "size":{
                          "width":193,
                          "height":220}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"2064b9bce32b4c8ba1e501f9ec5c4716",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}}},
            "location":{
              "x":70,
              "y":162},
            "size":{
              "width":49,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8e20df3f6d44caab6978ed58eae617c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":70,
                  "y":162},
                "size":{
                  "width":49,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Slider texts to Previous fade out 500ms slide right in 500ms wrap",
                      "panelsToStates":[{
                          "panelPath":["54cb98d1cb734d3d9c5758113c3857d2"],
                          "stateInfo":{
                            "setStateType":"previous",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "options":{
                              "animateOut":{
                                "easing":"fade",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideRight",
                                "duration":500},
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/card_-_home_page/u38.png",
            "mouseOver~":"images/card_-_home_page/u38_mouseOver.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "ebfb2981fb2a473591998f7096a5c368":{
      "scriptId":"u0"},
    "229397f2904c4338bc743f06d59b0c7a":{
      "scriptId":"u1"},
    "26cf5eeed7d84da1bc41e7e0c1f7c19c":{
      "scriptId":"u2"},
    "bf8b7df05e0b478790314df6b1479bd6":{
      "scriptId":"u3"},
    "82255c2ed0e04b79b8f33ae3e1a71b62":{
      "scriptId":"u4"},
    "c6bd52ed3a8f408ea8163b28b508e10b":{
      "scriptId":"u5"},
    "0b65c3c5be474b34942b48496b9d1831":{
      "scriptId":"u6"},
    "50bf048137924667a8fc5c813dc326b2":{
      "scriptId":"u7"},
    "df29119ed6b046bdbfea47f775eb45e8":{
      "scriptId":"u8"},
    "8b055a2e8875489d924ec6910d2f030d":{
      "scriptId":"u9"},
    "6810cb829cf74272bcf90903de100ab0":{
      "scriptId":"u10"},
    "517c1b04ceef47e7a4873100e3012b09":{
      "scriptId":"u11"},
    "e1428410928e4564ab4b04d8ebfa17fb":{
      "scriptId":"u12"},
    "cd4b6329e14446dda9838c14621e0989":{
      "scriptId":"u13"},
    "e66e2c03650a4506b145aff10a75041f":{
      "scriptId":"u14"},
    "d6d89e8ec17c4d819d8d5e3719a1c633":{
      "scriptId":"u15"},
    "5ec44c104f6a454bab89a78116c95ae0":{
      "scriptId":"u16"},
    "58b9e83c443c46bf878e8e9f65c4a1be":{
      "scriptId":"u17"},
    "c86f36d03ce448e1bd5b73840c8d8cce":{
      "scriptId":"u18"},
    "54cb98d1cb734d3d9c5758113c3857d2":{
      "scriptId":"u19"},
    "b85b1096ba9c40b695566ad0f4b5b879":{
      "scriptId":"u20"},
    "41d457efc2a342f6ae4302a7623f9d15":{
      "scriptId":"u21"},
    "946ccaca192141f7a1f65bd66b7bdd86":{
      "scriptId":"u22"},
    "6d43905bfaba419ca096ee72f7115d34":{
      "scriptId":"u23"},
    "400f6af72f3d43639a8ba18342b05117":{
      "scriptId":"u24"},
    "1b38f6ac55e04de4806f6ef3b58064d8":{
      "scriptId":"u25"},
    "01c1ae17c6204118ace9ff9b952584b9":{
      "scriptId":"u26"},
    "5cd7093eb9aa40b59fcee7e114917b57":{
      "scriptId":"u27"},
    "a6d21ea8275b49d09e6f659c202ce544":{
      "scriptId":"u28"},
    "c3ac1ca1d52a49abad25f16c200066c0":{
      "scriptId":"u29"},
    "eca056f5095f49bc80ffd9880abbb6fc":{
      "scriptId":"u30"},
    "7cbac792eda3414383d94ad958a44161":{
      "scriptId":"u31"},
    "049097ddfdc9488e823f6e4346c85969":{
      "scriptId":"u32"},
    "53562a64a15b4fbabea37a78af9697f4":{
      "scriptId":"u33"},
    "5ecaee34f32c402e9c87f948c2303c40":{
      "scriptId":"u34"},
    "94b5ebc76680400f886d690eef0ea6fb":{
      "scriptId":"u35"},
    "f39db920fb8842cca1e2e44033866089":{
      "scriptId":"u36"},
    "9f4ae739a1c84583a84bc50f67451b94":{
      "scriptId":"u37"},
    "f05e5a7189cc4e4594c9f59902235179":{
      "scriptId":"u38"},
    "256bec01c0d34179a305125a9b3fd33b":{
      "scriptId":"u39"},
    "415a19dec1b347168563399dfbcee1be":{
      "scriptId":"u40"},
    "a5b63f9c94df4ae089572fa0bbf816c1":{
      "scriptId":"u41"},
    "4b0812cdd8984cc384a1fe730b2d83be":{
      "scriptId":"u42"},
    "f13a0328d4574ae0a4842f0f33214bf5":{
      "scriptId":"u43"},
    "2d852fb4049240178c4418099436a48d":{
      "scriptId":"u44"},
    "6d7b297724214ae3b2099dde8ece4713":{
      "scriptId":"u45"},
    "1f14201c734645a1b4ef5d99c5218ed4":{
      "scriptId":"u46"},
    "c8d16d3af28c49988eb32d7463a40d5e":{
      "scriptId":"u47"},
    "1ec3896ac9d14820ad2deb18bd5135b1":{
      "scriptId":"u48"},
    "d6bb3d44684c4ad39bf5f74e3bca0b1d":{
      "scriptId":"u49"},
    "735a5a788e57441e8ee70200a9621496":{
      "scriptId":"u50"},
    "ee97077a8a77498885cf29630b74e971":{
      "scriptId":"u51"},
    "08ef55660d87405a81b5851c35ba285a":{
      "scriptId":"u52"},
    "3c12ea5c7ee14302a99dc54083a9e8a4":{
      "scriptId":"u53"},
    "4d5d29fafda54fd9acc6c9df0a8227e8":{
      "scriptId":"u54"},
    "00b251edc9d344d8826965e06802751a":{
      "scriptId":"u55"},
    "217dcc42c0e34278aff717b2bf923ff1":{
      "scriptId":"u56"},
    "2064b9bce32b4c8ba1e501f9ec5c4716":{
      "scriptId":"u57"},
    "a8e20df3f6d44caab6978ed58eae617c":{
      "scriptId":"u58"}}});